### ISSUE TITLE
Horario devido de cada linha

### ISSUE THREAD

**Issue by thonnycleuton** [tOOlmaker-equalsp/apiStransTHE#5]
Pessoal. Otimo trabalho ate aqui. 
Dei uma sacada na api e vi que ela disponibiliza dados sobre as Linhas, Veiculo e Paradas. 
Acontece que o dado que preciso seria a informacao sobre a hora devida que o onibus deveria estar em um determinado tempo que acho que deveria ser de responsabilidade da classe Linha. Tipo: o exato momento que ele deveria sair do ponto final, ou deveria estar no ponto perto da minha casa, por exemplo. As empresas trabalham com esses dados, é assim que os fiscais controlam cada viagem e, aparentemente, a API nao providencia isso. 
Alguma maneira de como contornar isso?
Obrigado.

**Comment by erickpassos** [comment]
Thonny, peço que leia a documentação da API rest original. Esses dados não são fornecidos diretamente via Rest. Nossa biblioteca apenas replica (e acrescenta funcionalidades, mas não dados) a API online original.

Os dados que você quer (dados estáticos sobre os horários da linha) são disponibilizados como arquivos textuais para download no site da API inthegra (Strans).
